[workspace]
members = [ "core", "radioscan", "api" ]

[workspace.metadata.nix]
systems = ["x86_64-linux"]

[workspace.metadata.nix.devshell]
language.c.compiler = "clang"
packages = ["matrix-synapse", "diesel-cli"]
