[package]
name = "basedcast"
version = "0.1.0"
authors = ["Rpgwaiter <rpgwaiter+git@based.zone>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpd = "*"
diesel = { version = "1.4.4", features = ["postgres", "numeric"] }
envmnt = "0.9.0" 
dotenv = "0.15.0" 
walkdir = "2.3.1" 
id3 = "0.5.0" 
globwalk = "0.8.1" 