FROM nixpkgs/nix-flakes


COPY . /var/radioscan

WORKDIR /var/radioscan

RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
RUN nix-channel --update

RUN nix build .#radioscan && ls result/

