[package]
name = "basedcast_core"
license = "gpl3"
version = "0.1.0"
edition = "2018"
authors = ["Rpgwaiter <rpgwaiter+git@based.zone>"]

[lib]
name = "basedcast_core"

[dependencies]
toml = "0.5"
mpd = "*"