table! {
    use diesel::sql_types::*;
    //use basedcast_core::db::enums::*;

    /// Representation of the `songs` table.
    ///
    /// (Automatically generated by Diesel.)
    songs (id) {
        /// The `id` column of the `songs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `title` column of the `songs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `track` column of the `songs` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        track -> Nullable<Int4>,
        /// The `game` column of the `songs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        game -> Text,
        /// The `artist` column of the `songs` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        artist -> Nullable<Text>,
        /// The `year` column of the `songs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        year -> Int4,
        /// The `system` column of the `songs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        system -> Text,
        /// The `is_public` column of the `songs` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_public -> Bool,
        /// The `bitrate` column of the `songs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        bitrate -> Int4,
        /// The `duration` column of the `songs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        duration -> Int4,
        /// The `filesize` column of the `songs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        filesize -> Int4,
        /// The `filename` column of the `songs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        filename -> Text,
        /// The `fullpath` column of the `songs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        fullpath -> Text,
        /// The `hash` column of the `songs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        hash -> Text,
    }
}
