FROM rustlang/rust:nightly

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    clang \
    libclang-dev \
    llvm-7-dev \
    pkg-config  && \
    rm -rf /var/lib/apt/lists/*
