FROM rustlang/rust:nightly

# COPY . /var/radioscan

# WORKDIR /var/radioscan

RUN apt-get update && apt-get install -y libavutil-dev libavformat-dev libclang-13-dev


# RUN nix build .#radioscan && ls result/