name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: rpgwaiter
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Copy config
      run: mv settings.toml.example settings.toml
    -
      name: Build & Push Api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./api/Dockerfile
        push: true
        tags: rpgwaiter/basedcast_api:latest
    -
      name: Build & Push Api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./radioscan/Dockerfile
        push: true
        tags: rpgwaiter/basedcast_radioscan:latest
